sudo: required
dist: trusty
language: python
matrix:
    include:
        - python: 2.7
          env: TEST_MODE=PEP8
        - python: 2.7
          env: TEST_MODE=GENERAL
        - python: 3.6
          env: TEST_MODE=GENERAL
        - python: 2.7
          env: TEST_MODE=EXTRA
        - python: 3.6
          env: TEST_MODE=EXTRA

# command to install dependencies
install:
  # code below is taken from http://conda.pydata.org/docs/travis.html
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - travis_wait 30 conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - travis_wait 30 conda install mkl mkl-service
  - travis_wait 30 pip install -r requirements.txt
  - export PYTHONPATH=$PWD:$PWD/src:$PYTHONPATH

  # set library path
  - export LD_LIBRARY_PATH=$HOME/miniconda/envs/test-environment/lib/:$LD_LIBRARY_PATH

  # install TensorFlow (CPU version).
  #  - pip install tensorflow

# command to run tests
script:
  - export MKL_THREADING_LAYER="GNU"
  - echo -e "Running tests with the following config:\n$(cat ~/.keras/keras.json)"
  - if [[ "$TEST_MODE" == "PEP8" ]]; then
      PYTHONPATH=$PWD:$PYTHONPATH pytest --pep8 -m pep8 -n0;
    elif [[ "$TEST_MODE" == "GENERAL" ]]; then
      PYTHONPATH=$PWD:$PYTHONPATH pytest -s tests/*py 2>&1 ;
    elif [[ "$TEST_MODE" == "EXTRA" ]]; then
      PYTHONPATH=$PWD:$PYTHONPATH pytest -s tests/extra/ 2>&1 ;
    fi
