sudo: required
dist: bionic
language: python
matrix:
    include:
        - python: 3.6
          env: TEST_MODE=PEP8
        - python: 3.6
          env: TEST_MODE=GENERAL
        - python: 3.6
          env: TEST_MODE=EXTRA

# command to install dependencies
install:

  - travis_wait 30 pip install .
  - pip install pytest pytest-cache pytest-cov pytest-forked pytest-pep8 pytest-xdist --progress-bar off

# command to run tests
script:
  - if [[ "$TEST_MODE" == "PEP8" ]]; then
      PYTHONPATH=$PWD:$PYTHONPATH pytest --pep8 -m pep8 ;
    elif [[ "$TEST_MODE" == "GENERAL" ]]; then
      PYTHONPATH=$PWD:$PYTHONPATH pytest -s tests/general/ 2>&1 ;
    elif [[ "$TEST_MODE" == "EXTRA" ]]; then
      PYTHONPATH=$PWD:$PYTHONPATH pytest -s tests/extra/ 2>&1 ;
    fi
